# Generated by Django 5.2 on 2025-04-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieMod',
        ),
    ]
