# Generated by Django 5.2 on 2025-04-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movie_moviemod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mob', models.IntegerField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
            ],
        ),
    ]
