# Generated by Django 4.2 on 2025-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_age', models.IntegerField()),
                ('emp_sal', models.FloatField()),
                ('emp_add', models.CharField(max_length=20)),
            ],
        ),
    ]
