# Generated by Django 4.2 on 2025-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student9767',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.FloatField()),
                ('add', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Empl',
        ),
    ]
