# Generated by Django 4.2 on 2025-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('elig', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('add', models.CharField(max_length=80)),
                ('skills', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Koljobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('elig', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('add', models.CharField(max_length=80)),
                ('skills', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Punejobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('elig', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('add', models.CharField(max_length=80)),
                ('skills', models.CharField(max_length=50)),
            ],
        ),
    ]
